### ISSUE TITLE
supersized with java cookie

### ISSUE THREAD

**Issue by bernte** [buildinternet/supersized#10]
hi sam.. first wanna say your script is awesome :D second.. my english is not very well but i try to explain my question

i watched your 2 scripts Supersized 3.1.3 Slideshow & Supersized 3.1.3 Core/Random (Supersized Flickr 1.1.2 is not important to me) 

i working on a new photogallery for my website.. and i use your "slideshow" as (REAL!!) background for all my sites (about, contact, pictures... etc.) but now i have the problem when i am for example on about.php i got picture1.. then loading picture 2...... then i click on contact.php and it starts by picture1... and so on... i know that i can use the random function! but the problem is an other :D
when i dont want to use the slideshow (visitor view) or i love the current background then i click pause! (what works really good :-) ) but when i do now a sitechange (for example from contact.php to gallery.php) the pause function is gone and the slideshow starts again by zero :D
is it possible to do that with cookies? 
i saw this on a templatesite. (pause works on sitechange/reload) maybe you can take a look at the site... http://tinyurl.com/slideshow-with-cookies 
he works with jQuery Cookie (https://github.com/carhartl/jquery-cookie) but i have no idea how it works :D :D

is it possible to add this feature?? :D  if so, you can call it for example: Supersized 3.1.3 Cookie Oversized :D
hope you understand my problem.  
I would take part at donation if its possible :D

best regards

bernte

/// another suggestion... when you disable javascript at Supersized 3.1.3 Slideshow you can see the controll buttons

maybe you have an better idea but i did it with:  

```
<div id="controls-wrapper">
    <script type="text/javascript">$('<div id="controls"><div id="navigation"><img id="prevslide" src="img/back_dull.png"/><img id="pauseplay" src="img/pause_dull.png"/><img id="nextslide" src="img/forward_dull.png"/></div></div>').appendTo('#controls-wrapper');</script>
</div>
```

**Comment by samdunn** [comment]
At this time, I don't see myself adding cookie functionality for the sake of maintaining consistency across multiple pages. It seems like a better approach might be to dynamically load in the pages without refreshing. Best of luck.
