### ISSUE TITLE
Display images within a container

### ISSUE THREAD

**Issue by ghost** [buildinternet/supersized#100]
Hello,

I am having a bit of trouble trying to display the image within a certain area of my website.

Ideally I would like the images to begin below the top header, to the left of the navigation, and above the thumbnail tray.

Is this currently possible? My images are being cut off too much on the top and bottom.

**Comment by samdunn** [comment]
If you change all references of position:fixed to position:absolute, you can then specify a size for #supersized and #supersized > li
