### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by s10wen** [buildinternet/supersized#101]
Not really an 'issue' but added a 'Feature Request' page to the wiki:
https://github.com/buildinternet/supersized/wiki/Feature-Request

Would be awesome if this is possible, I'm trying to integrate with WordPress, so content can be easily managed via the cms.

**Comment by samdunn** [comment]
You can do this in the current version using the getField option to pull in an ID for each slide and hide/show the relevant HTML. You'd need to add this to the theme js (particularly the beforeAnimation and afterAnimation). It is discussed throughout the comments of the blog post as well.
http://buildinternet.com/2011/07/supersized-3-2-fullscreen-jquery-slideshow/

Alternative option is discussed here:
http://stackoverflow.com/questions/7772295/supersized-show-a-div-depending-on-the-slide

**Comment by s10wen** [comment]
Hi, sorry if I'm missing something but the link:
http://buildinternet.com/2011/07/supersized-3-2-fullscreen-jquery-slideshow/

shows it has 1107 comments, but I can only seem to view about  the last 10 of them.

Also the 2nd link:
http://stackoverflow.com/questions/7772295/supersized-show-a-div-depending-on-the-slide

suggests adding the HTML with jQuery:

<pre>$("#id_of_div").html("Any <b>HTML</b> content here");</pre>

or specifying the current id:

<pre>// current slide is #5
if (vars.current_slide == 5) {</pre>

I'd rather avoid these options if possible, so that going forward it can be edited via the WordPress cms.

Will have a play about with the getField and beforeAnimation / afterAnimation and see how I get on with that.
