### ISSUE TITLE
Add a footer below the gallery

### ISSUE THREAD

**Issue by stephaniebane** [buildinternet/supersized#104]
How can I make a footer appear below the gallery? I tried to set the height on the container, so it's, let's say, only 700px tall. Then, I want my footer to fall below that. So, there will be a scroll bar to see the rest of the content and the image will appear behind the main area and the footer is always on the bottom, below the actual images. 

Currently when I put the footer in and set a height, it's just putting it on top of my image and hiding a hefty portion of it. Any help would be appreciated. Thanks!

**Comment by samdunn** [comment]
If you change all instances of position:fixed to absolute, you can set dimensions on #supersized and #supersized > li.

Hope this helps!

**Comment by stephaniebane** [comment]
Thank you!
