### ISSUE TITLE
Change links to open in the same window

### ISSUE THREAD

**Issue by stephaniebane** [buildinternet/supersized#105]
I've tried making modifications to the slide_links element, but nothing changes. Even when I make it 'false' it still has a link and opens in a new window. I'd like to have the link open in the same window. Is that possible? 

Thank you!

**Comment by samdunn** [comment]
This should help:http://buildinternet.com/project/supersized/docs.html#new_window

**Comment by stephaniebane** [comment]
Thanks for the response! I'll give it a try.
