### ISSUE TITLE
Displaying Thumbnail carousel

### ISSUE THREAD

**Issue by ghost** [buildinternet/supersized#137]
This is our first implementation of Supersized and we can't seem to figure out how to display the thumbnails carousel seen on the demo. We've matched the options but ours never shows the "up" icon to expose the thumbnail menu.

Is there something I'm missing?

```
$.supersized {
    slide_interval: 3000
transition: 1
transition_speed: 700
slide_links: 'blank'
thumb_links: 1
thumbnail_navigation: 0
slides: [slides array (includes "thumb" property)]
}
```

Images and titles show up fine. Just no thumbnails.

**Comment by bokkagroup** [comment]
This is an issue with the usage of .toggle() being depreciated in jQuery 1.9.1. Switching to 1.8 fixed everything.
