### ISSUE TITLE
Bug with IE 6,7,8, Image is distorded

### ISSUE THREAD

**Issue by jstawski** [buildinternet/supersized#16]
I've noticed that with IE 6,7, and 8 (confirmed with 6 and 8) sometimes when the image is loaded for the first time the image becomes distorded. After a reload of the page the image comes up right.

Distorded on first load http://twitpic.com/5g79w3
Right on second load: http://twitpic.com/5g79nx

**Comment by samdunn** [comment]
Make sure you are running the latest version, 3.2.0, which should fix IE distortion issues. IE6 is not supported by Supersized, or Google for that matter!

**Comment by JakeDK** [comment]
Hej Sam great work, but could u explain how u fixed the IE problem?

**Comment by samdunn** [comment]
When an image is first loaded it's dimensions are stored in the slides array before it is resized. Previously, this did not happen, so resizing could have hiccups if the image changed sizes before completely loading.
