### ISSUE TITLE
font to font-size

### ISSUE THREAD

**Issue by G470** [buildinternet/supersized#18]
Hi, had a small problem with the font size in thesupersized.shutter.css
 #slidecounter and #slidecaption have a font: 14px; property.
This is causing a css error in google chrome. 
Maybe you can switch to font-size: 14px;

Beste wishes: G470

**Comment by samdunn** [comment]
Hey there,

I'm not seeing a CSS error resulting from this - I'm using the shorthand font property to define more than just font-size, so there shouldn't be an error. Did you customize the CSS?

**Comment by G470** [comment]
Yes, no error on the test page. And I also think it´s a good idea to use the shorthand method. 
Maybe this is just a strange chrome bug.
only "font:14px;" gives a error.
"font: 14px "Helvetica Neue", Helvetica, Arial, sans-serif;"
is ok... so I think it's solved.
Maybe I had some old styles. Sorry for false alarm :)
