### ISSUE TITLE
HELP: Not loading Flickr Album

### ISSUE THREAD

**Issue by casasptbr** [buildinternet/supersized#182]
Hello,

Since last week the supersized script is not loading my flickr album, i didn't change any features for this to happen. How can i put this working properly?

Here's the URL 
http://casageres.nobrinde.com/
http://casageres.nobrinde.com/redondezas/
http://casabrasil.nobrinde.com/

Can someone help me out?
Thank you very much

**Comment by micrgl** [comment]
the same here. didn't change anything to my site, but the flickr-album suddenly won't load anymore. help would be highly appreciated.
thanks!

**Comment by micrgl** [comment]
bug found! apparently the flickr-api only suppports a secure connection (see: https://code.flickr.net/2014/04/30/flickr-api-going-ssl-only-on-june-27th-2014/ ) anymore. to solve the problem follow these steps:
1) navigate to your site and find the folder named "js". open it.
2) there should be a file named supersized.flickr.1.1.2.js (numbers might differ)
3) open the file in your preferred editor, go to line 138 and edit the _var flickrURL_. change it from **http** to **https**.
4) repeat step 3 for lines 142, 145, 148

**Comment by zachdunn** [comment]
Resolved via #183
