### ISSUE TITLE
Single Image Not Filling Screen

### ISSUE THREAD

**Issue by peepshow** [buildinternet/supersized#2]
When there is only one image loading in it does not fill the screen. It works fine with multiple images however. 

The site I’m building is developed on WP and allows for one or more images to be used as a feature for each post so the core version is not enough.

I have already raised this issue on the blog entry for Supersized but thought I'd add it here for the sake of tidy house keeping (not pestering).

Thanks again 
Regan

**Comment by samdunn** [comment]
Update 3.1.1 takes care of this issue, thanks for bringing it up!

**Comment by peepshow** [comment]
Awesome thanks Sam.
