### ISSUE TITLE
playToggle is not working allways

### ISSUE THREAD

**Issue by nicmare** [buildinternet/supersized#21]
just noticed that playtoggle seems not to affect anything during an active transition.
supersized 3.2.1. with jquery 1.6.1.

**Comment by samdunn** [comment]
During a transition, the variable inAnimation is marked as true, which prevents pausing to stop animation build-up.

**Comment by nicmare** [comment]
yea okay thats good. but it would be smarter to pause the slideshow after animation is completed :)

**Comment by timoklok** [comment]
Have you found a workaround for this perhaps?
