### ISSUE TITLE
Firefox broke slideshow

### ISSUE THREAD

**Issue by gasfax** [buildinternet/supersized#23]
Hi Sam,
I noticed that the bug you fixed with 3.2.3 is already affecting Firefox (5.0 and 5.0.1) on Mac OsX 10.6.7 (I din't done any test on Windows)

I've done some some tests with your online demo (http://buildinternet.com/project/supersized/slideshow/3.2/fade.html) to prevent any personal implementation error: the slideshow randomly stops at 2nd/3rd slide sometimens with black page.

Sorry for my bad english.... and thank you for your amazing work!

-gas

**Comment by juanmiglesias** [comment]
Hi Sam, I just checked 3.2.3 on firefox for windows, this time FFv3.6.18 and its affected with this issue too... i tought at first maybe it was a noConflict() issue with mbMenu.js or lightwindow.js, but its working if a change to supersized 3.1 (as i have it before), also tried it on Chrome and iE9 with 100% issues free,  32bit version of both, im on 64bit win7

the issues i see on Firefox are as follow:
1. it seems like random messes around, even if its turned off, i get different ordered images after 1 loop.
2. sometimes i get a black screen and the script just stops working, slide counter, progress bar, and the cirlces for navigation all seem to stop, only works the open up thumb navigation, hovering over the thumbs, but no way of getting back the bg images again.

hope this help a bit, im really new at scripting and found your code one of the best for newbies like me. 
thanks for sharing your knowledge.

**Comment by samdunn** [comment]
Thanks - I would use version 3.2.1 while I look into this.

**Comment by samdunn** [comment]
The 3.2.4 release should hopefully resolve this - it did in my testing!

**Comment by gasfax** [comment]
Hi, Sam... now it works like a charm! 

Thank you again.

-gas

**Comment by juanmiglesias** [comment]
wow!  that was fast.. :D everything seems fine now!
