### ISSUE TITLE
Vertical Alignment problem with the second slide (if using only 2 images)

### ISSUE THREAD

**Issue by meydjer** [buildinternet/supersized#24]
Issue with the version 3.2.4.
Mac OS X 10.6.7
Browsers: Firefox 5, Chrome 12, Safari 5 and Opera 11.
Screen Resolution: 1920x1080.

If I use only 2 images in the slider, Supersized generates 2 images inside the second list item (supersized > li.slide-1 > a*2 > img). In this case, if I use the Vertical Centering, the second slide appears displaced.

**Comment by webponce** [comment]
I think i'm seeing something similar. When there are only two items in the image list, the second image on resize seems to present a copy of the image below, which obscures the main image in the background.

Screenshot at: http://grab.by/aEYM

Testing on Chrome on Windows 7
seems okay with 1 or 3 items.

**Comment by meydjer** [comment]
@webponce

Exactly the same problem. Thanks for your screenshot.

**Comment by imanthonyholmes** [comment]
If you're only using 2 slides, just double your slides to 4 and still have it alternate every other. Quick fix to keep the same two images alternating.

**Comment by samdunn** [comment]
Sorry for the massive delay guys - I just updated to 3.2.5 where I included a fix for this. You should all be good now!

**Comment by meydjer** [comment]
Thanks! You rock.

I'll try it soon.
