### ISSUE TITLE
Uncaught Type Error

### ISSUE THREAD

**Issue by GregMcGee** [buildinternet/supersized#30]
Cannot call method 'getField of undefined
a.supersized.d._start
a.supersized.d._build
a.supersized.d.init
a.supersized
(anonymous function)
c.extend.ready
L

I get this when trying to run  the core/random code 3.2.4

No images appear.

**Comment by samdunn** [comment]
The core version of Supersized doesn't support API calls - if you're looking for this functionality you can use the slideshow version and adjust it to mimic the core random setup.

**Comment by katsudone** [comment]
Hi, I get exactly the same error using the slideshow version (3.2.7).
I'm not calling apis, just trying to use it as it is, as shown in the slideshow sample.
Can you please help me?

Thanks.

**Comment by brandoniffert** [comment]
@katsudone Make sure your $.supersized call is in a document ready function.

**Comment by katsudone** [comment]
Thanks.

**Comment by dgtlmoon** [comment]
Seems to be still a bug, I'm on 3.2.7 and tried using the slideshow and regular version, library is being called from my document.ready ..

**Comment by MichaelFBA** [comment]
Similar bug - 3.2.7.

I found a fix. Maybe not be applicable to everyone.

I am loading my images from the DOM so I needed to make sure the array was populated before supersized.js ran. I just put it in a callback.

```
jQuery(document).ready(function ($) {

function superSizeSetup(callback){
    var slideImages = [];           
    $(".background-images img").each(function() {
        var obj = {};
        obj.image = $(this).attr('src');
        slideImages.push(obj);
    });
}

superSizeSetup(function() {
   $.supersized({
    start_slide        :   0,           // Start slide (0 is random)
    vertical_center      :   1,         // Vertically center background
    horizontal_center  :   1,           // Horizontally center background
    fit_landscape      :   0,
    fit_portrait           :   0,
    slides             :    slideImages

});
});

});
```

**Comment by iwayanwirka** [comment]
I solve the problem by calling the supersized function inline on header of the html file instead of inside js file.
