### ISSUE TITLE
webkit issue: choppy animation of fade transitions 

### ISSUE THREAD

**Issue by dsalkanovic** [buildinternet/supersized#33]
HI,

I have problem with choppy display of transition animation of slider ... and i see its "general" problem of supersized which is very good script is we dont mind its incompability with webkit browsers ...

u can see it here [ http://buildinternet.com/project/supersized/slideshow/3.2/fade.html ] i u try to open it in safari ...

has any1 solved this issue ?

**Comment by samdunn** [comment]
This is a result of a your computer speed and the current limitations of the browser. Webkit browsers currently don't allow the adjustment of image quality, which prevent speed optimizations possible in Firefox and IE. Short of CSS3 in a future release, there is not much we can do at this point in the game.

**Comment by mrporsch** [comment]
There is a Problem with the image-resizing. Set fixed dimensions and u will see a smooth transition.
