### ISSUE TITLE
iPad scrolling background not working

### ISSUE THREAD

**Issue by miquil** [buildinternet/supersized#39]
On the iPad the background doesn't seem to scroll with the screen when you scroll down on a longer page. In the online demo: http://buildinternet.com/project/supersized/core/3.2/core.html when I scroll down I get a black background at the bottom. 

Screenshot iPad: http://www.clusive.nl//labs/screenshots/ipad_supersized.png

Can this be fixed?

**Comment by samdunn** [comment]
iOS 5 is the first version which will support position:fixed; which means we can't gracefully handle scrolling until the update. That being said there are some hack-around ways to fake position:fixed on iOS which can be found with some Googling if this is a dealbreaker for your current setup.
