### ISSUE TITLE
[feature] Adding a function to show a specific image

### ISSUE THREAD

**Issue by amrnt** [buildinternet/supersized#4]
I'm building a website with one single page... Supersized is such an awesome plugin, an I really want to use it.

In my website for example I have `3` pages [Home, About, Contact] and for each theres a image describe them.

Is there any way to call a function to call the image as the background?

I see we can go `Next` and `Prev` with images... It'll be cool if I can go to a specific image by its id in the slides array!

**Comment by samdunn** [comment]
This is something that will be addressed in future version of the script - currently it's not an included feature. It's on my to do list!
