### ISSUE TITLE
IE stretches the image.

### ISSUE THREAD

**Issue by JakeDK** [buildinternet/supersized#40]
When I enter the page for the first time it stretches the image in IE7/8/9 but when I reload or enter the url again, everything looks fine.
I am useing an older version af supersized and I can't updates it because I have modifyed it. So hope you can help me.
You can see the problem on this site: http://www.triptrap.dk/ 

By the way love your work and have been using this script a lot! Also I want to share my modifyed version which has a bullet-tracking-system, I will post it when it's setup in fiddle

**Comment by samdunn** [comment]
This is something that I updated with newer releases - unfortunately it's not just a quick copy paste, I would encourage you to try to update (or swap in) the new Supersize - it's really the best way go about it (apologies to your customizations : (.

PS. Thanks! Awesome to hear.
