### ISSUE TITLE
Doesn't work in IE9

### ISSUE THREAD

**Issue by Gkuurstra** [buildinternet/supersized#42]
Hello,

I'm using this great plugin on my wesbte: www.identysign.nl
In every browser it works really nice, only not in IE9
The image is loading, but it won't stretch to fullscreen.

How can I fix this?
I couldn't find a solution on this website.

I hope you could help me out with this!

**Comment by samdunn** [comment]
This is not a problem with Supersized, you need to check out any errors using the developer tools on IE9.

SCRIPT5007: Unable to get value of the property 'corner': object is null or undefined 
www.identysign.nl, line 103 character 5

**Comment by Stoffel84** [comment]
Hi,

on <a href="http://gwinner-pforzheim.de">gwinner-pforzheim.de</a> everything works fine in all browsers but not in ie lower version 10.
Supersized is displayed below my main divs.

I hope you could help me out with this - thank you
