### ISSUE TITLE
Ability to send images as variable

### ISSUE THREAD

**Issue by vimixto** [buildinternet/supersized#43]
I`m trying to initiat gallery manual by "click" event. And the main problem is how to send string with images into supersize gallery?

Detailed, I`m trying to do this:
1. User clicks on element and ajax-query begins
2. Server gives back all needable params with json (images)
3. Responce processing and forms into needable form
4. supersized gallery initiates with new parameters

example code:

$.getJSON('somepath', function(data){
var images = '';
//decoding json and forming images into 'images' variable in needable form  
//and now we have variable 'images' for example as this:
images = "{image : 'http://buildinternet.s3.amazonaws.com/projects/supersized/3.2/slides/kazvan-1.jpg', title : 'Image Credit: Maria Kazvan', thumb : 'http://buildinternet.s3.amazonaws.com/projects/supersized/3.2/thumbs/kazvan-1.jpg', url : 'http://www.nonsensesociety.com/2011/04/maria-kazvan/'},                       {image : 'http://buildinternet.s3.amazonaws.com/projects/supersized/3.2/slides/kazvan-2.jpg', title : 'Image Credit: Maria Kazvan', thumb : 'http://buildinternet.s3.amazonaws.com/projects/supersized/3.2/thumbs/kazvan-2.jpg', url : 'http://www.nonsensesociety.com/2011/04/maria-kazvan/'}"; 
//and trying to initiate the gallery
$.supersized({slides:[images]});
//but it doesn`t work  
});

sorry if I`m posting not an 'real matter for you' issue, but I really don`t know what to do and I want to use this gallery
thanks

**Comment by joshmosh** [comment]
I think you're going to want to do something more structured in your javascript. Maybe something like:

``` javascript
$.getJSON('url', function(response) {
  var images = [];

  // Assuming response is an array, let's loop over them and build an object
  $.each(response, function(index, value) {
    var image = {
      image: value.image,
      title: value.title
    };

    // Push new image object to images array
    images.push(image);
  });

  // After loop is finished, init supersized plugin
  $.supersized({
    slides: images;
  });
});
```

The key is just making sure you run the plugin after you have data.

**Comment by vimixto** [comment]
Really thank you for your reply!

My problem was in lack of knowledge - I was constructing var 'images' as a string but not as array!

**Comment by samdunn** [comment]
Seems like you got a good response - loading sets of slides without page refresh is something I plan to explore in a future version.

**Comment by marcoalexpinheiro** [comment]
Thanks a lot, you saved my day!
