### ISSUE TITLE
Using Apostrophes In Title

### ISSUE THREAD

**Issue by chrishadley** [buildinternet/supersized#49]
Hi there,

I've found that using apostrophes in the image title will break the slider.

For example:

```
{image : 'http://buildinternet.s3.amazonaws.com/projects/supersized/3.2/slides/kazvan-1.jpg', title : 'Chris' Party', thumb : 'http://buildinternet.s3.amazonaws.com/projects/supersized/3.2/thumbs/kazvan-1.jpg', url : 'http://www.nonsensesociety.com/2011/04/maria-kazvan/'},
```

Is there a work around for this?

Thanks

**Comment by samdunn** [comment]
You need to escape the character using a "\" right before.

http://forums.asp.net/t/1047952.aspx/1
