### ISSUE TITLE
Transition in first image

### ISSUE THREAD

**Issue by kennymcnett** [buildinternet/supersized#50]
I've seen several requests in posts and forums for how to add a transition to the first image loaded. Specifically, a fade. But it would make sense to apply whatever transition is assigned in the vars. 

I've tried unsuccessfully to make it work. 

Can someone offer a solution?  Thanks!

**Comment by dudieboy** [comment]
Me too. I'm using the core.html version and want the BG image to fade in slowly for about two seconds, no further transitions.

**Comment by samdunn** [comment]
You can make these edits in the base Supersized JS file. Look for the section at the beginning for "launch", more specifically:
base.$el.css('visibility','visible');

You would need to alter this line (which just shows the image by changing the CSS property) to be a fade instead.

**Comment by kennymcnett** [comment]
Thanks, samdunn. You got me going in the right direction, but .fadeIn() doesn't work here because the image was hidden via visibility:hidden, which is a CSS property (source: http://www.w3schools.com/jquery/eff_fadein.asp), but we can hide() it then fadeIn() instead. Hacky, but it works.*

You're editing the core script, so make a copy of the full (not minified) version of supersized.3.2.6.js and rename it supersized.3.2.6.custom.js

Then, on line 206 (which is what samdunn pointed out):

change
base.$el.css('visibility','visible');

to
base.$el.css('visibility','visible').hide().fadeIn(1500 ); // 1500 is the transition speed

That tells the CSS to make the object visible, then it hides it with jquery, then fades it in with jquery. 

Change 1500 to whatever transition speed matches your pages. Then save and upload your new supersized.3.2.6.custom.js to your site. Remember to update the link to the script in your webpage <head> with the new filename, like so:

script type="text/javascript" src="js/supersized.3.2.6.custom.js"

*The only hiccup I've seen is in a version of IE where the first image jumps slightly after fading in. It's not ideal, but it's better than no fade on the first image (in my scenario, not all scenarios). It's fine on Chrome and FF.

**Comment by gutierrezfredo** [comment]
it worked like a dream com true... Thank you kennymcnett !!!

**Comment by diogo15** [comment]
Thanks  kennymcnett!
