### ISSUE TITLE
Vertical centering error

### ISSUE THREAD

**Issue by Asarew** [buildinternet/supersized#52]
Hi,

every middle slide has a problem with centering verticaly,
the slide ends up aligned from the top down.
every slide has the same resolution but the middle slide isn't working correctly

**Comment by samdunn** [comment]
If you have a problem that doesn't appear in the demo, please include a link, so I can determine if this is a Supersized issue or a problem with your implementation.

**Comment by Asarew** [comment]
the link is http://flyingstarentertainment.com
Thanks for the quick reply

**Comment by samdunn** [comment]
You appear to have the option for vertical centering turned off, I don't quite know what you mean by middle slide, but your install seems to be working as intended.

**Comment by Asarew** [comment]
ohh im sorry, i had to turn the vertical centering off to compensation for the error.

i just turned it on again

**Comment by samdunn** [comment]
I'm still not seeing an issue, I'm using Chrome
