### ISSUE TITLE
Link not working on Safari?

### ISSUE THREAD

**Issue by ispeakwhale** [buildinternet/supersized#56]
Hello,

Why is it that in the demo you can have a full screen link on the background and it works but when I install it on my website I cannot access the link? The link itself it not existing. What did I miss?

Thanks!

**Comment by samdunn** [comment]
Odds are you have a div blocking the user from clicking the background - if you define widths (or use position:absolute) that should correct the issue.

**Comment by ispeakwhale** [comment]
I believe this is not the problem since i have NO div anywhere. All I want on my page is a fullsize background with the link therefore this is all I have in my index but link is still not working on Safari. why?
