### ISSUE TITLE
flickr api key not working consistently

### ISSUE THREAD

**Issue by jampa** [buildinternet/supersized#59]
Hi,

I have my api key and everything I need and it only works sometimes! But I have to refresh over and over to get it to come up to where it is actually pulling and displaying the images. It seems to happen more when using the set and group ID's. When I use the user id it becomes a little more consistent, but not much.

Is there something I am overlooking or is this a known issue?? Any help would be appreciated.
Thanks.

**Comment by samdunn** [comment]
At this time, we've opted to discontinue support for Flickr going forward. Apologies!
