### ISSUE TITLE
JavaScript error in IE7/8

### ISSUE THREAD

**Issue by honestcode** [buildinternet/supersized#60]
When using Supersized in IE7 and 8, we receive the following error:

```
SCRIPT5007: Unable to get value of the property 'url': object is null or undefined 
supersized.3.2.7.js, line 149 character 6
```

You can test it here: http://staging7.honestcode.com/yachts/pyewacket-2/

We specify URL parameters when calling Supersized. Of course, everything works perfectly in IE9, along with Chrome, Safari, Firefox, et. al.

Any help would be much appreciated. :)

**Comment by samdunn** [comment]
This issue seems specific to your implementation, not an overall plugin issue, since this is not a problem I've seen on the included demo pages.

Offhand I don't have a recommendation, aside from double checking it has been implemented properly.

**Comment by honestcode** [comment]
I am officially a bonehead -- I had an extra comma at the end of my images array. Sorry to trouble you. :)
