### ISSUE TITLE
Ubuntu Chrome, laggy transitions

### ISSUE THREAD

**Issue by mrporsch** [buildinternet/supersized#62]
Hey

Has anyone noticed the above issue? Seems that the preloading doesn't work (only for last und next image).

Is there a solution? 

Thx

**Comment by brettshumaker** [comment]
Yes, I have...in Chrome and Safari. I believe it's this same issue: https://github.com/buildinternet/supersized/issues/33

I don't buy the "result of a your computer speed" of the response. I'm running a 27in iMac with 2.8 i5 processor and 4gb ram and have never had any problems with javascript transitions in Chrome before. It looks like it's only doing 3-4 steps during the transition.

**Comment by mrporsch** [comment]
It's the Image-Scaling. 

If images have exactly the size they are displayed, the transition runs smooth. Giving the images a fixed size (via css) worked for me, as I know the display-size, but I think it's not the idea of supersized ;-)

**Comment by brettshumaker** [comment]
Yep...I think that defeats the purpose. :)

**Comment by samdunn** [comment]
You guys seem to have sorted this out. I have noticed difference in performance across different machines, which leads me to believe that computer speed is a factor.
