### ISSUE TITLE
inconsistent image sizing (Chrome / Firefox)

### ISSUE THREAD

**Issue by rubensun** [buildinternet/supersized#65]
I'm running into issues with supersized an inconsistent sizing.
I've saved 5 images all with the same image dimensions (1660x1107)
but I'm finding that both under Chrome and Firefox, Supersized is generating different image sizes in a session that causes for some images to look perfect and others to be distorted and stretched. 

http://imageshack.us/photo/my-images/822/inconsistantsizing.png/

I'm not sure if it's because I'm using this plugin with foundation (responsive web framework) or if there's something fishy with my implementation flat out.

Any advice would be appreciated.

**Comment by rubensun** [comment]
note the differences in the height of the images.

here's the link to the firefox screen grab:
http://imageshack.us/f/13/inconsistantsizingff.png/

**Comment by samdunn** [comment]
Rubensun,

This is not something that I've encountered (the demo pages don't seem to have this issue) which would lead me to believe it might be one of the other causes you mentioned.

**Comment by rubensun** [comment]
## any pointers on how to trouble shoot this?

ruben sun :: interactive art director
       tel. 312.804.2930
       email. bacon@rubensun.com

www.rubensun.com  |  www.linkedin.com/in/rubensun
twitter.com/sunruben

On Mon, Mar 26, 2012 at 09:36, Sam Dunn <
reply@reply.github.com

**Comment by samdunn** [comment]
Offhand, maybe you have CSS that conflicts with img within Supersized. I would try removing out your responsive web framework and see if the problem persists.

**Comment by brettshumaker** [comment]
I had this same problem rubensun. If you're still looking for the culprit, mine was that img had max-width set to 100%

**Comment by neurosismann** [comment]
I'm having this issue also. Not using a framework and I don't have max-width set to 100%.
