### ISSUE TITLE
Can I use your script in Themeforest

### ISSUE THREAD

**Issue by Y2ok** [buildinternet/supersized#67]
Hello,

I'm about to launch my template on themeforest, and I have a question - can I use your script for Themeforest template? I will leave all copyright information in Javascript and CSS files, also I would like to use default next/previous images, and other images that are inside supersized pack for my theme, is that available too? 

Hope, that I can use it for free ;)!

If you don't know what's themeforest - it's a market, where people can buy your themes (websites), with all data, so in this case, they will buy my template with supersized scripts and images, so I would like to ask if I'm able to leave part of the next/previous buttons e.c. in the theme and also the css and javascript files with copyright in the top of the files?

Best regards,
Y2oK

**Comment by samdunn** [comment]
I include licenses in the download for this exact question - take a look, should be fine!
