### ISSUE TITLE
Supersized on Ipad  - problems with transitions

### ISSUE THREAD

**Issue by Pushplaybang** [buildinternet/supersized#77]
Hey there, 

supersized works great on multiple devices in a new website I'm building  - all in fact except the Ipad (tested on an ipad2).  fade splatters and splutters along, any help or insight would be greatly appreciated.

P:)

**Comment by samdunn** [comment]
This is something I'm hoping to clean up with CSS transitions as a fallback in the future. I've noticed a lot of jQuery animations are subpar on iOS devices.

**Comment by Pushplaybang** [comment]
funny enough, it works brilliantly on the iphone 3 and 4 that I've tested it on, and I managed to get it to smooth out at one stage on another ipad, but more of an edge scenario( in some very messy code that broke everything else) than a workable solution, I'm getting back on this project this week will let you know what I find, overall an awesome plugin btw.
