### ISSUE TITLE
There is some way to NOT resize the image ?

### ISSUE THREAD

**Issue by hugodias** [buildinternet/supersized#80]
How can we leave the image to full size without resizing it? I mean, leaving only the visible part appearing by the browser, much like 'overflow: hidden'

**Comment by samdunn** [comment]
You would need to go into the resizeNow function in supersized.3.2.7.js and strip out all of the image resize functionality.

**Comment by hediej** [comment]
Hello,

For a novice developer, is there any tools you can lead me to in order to correctly strip out the 'resizeNow' functionality? Whatever I have tried basically 'breaks' the entire script :-/
Thank you!!
