### ISSUE TITLE
new_window as default only

### ISSUE THREAD

**Issue by BOXNYC** [buildinternet/supersized#9]
The [slides] setting variable needs to include an optional link's target value. Then use the new_window setting variable as a default link target. Then it could be set like this:

$.supersized({
    new_window: 0,
    slides: [
        {image:'http://apple.com/apple.jpg', title:'My Image', url:'http://apple.com', target:'_blank'},
        {image:'/local/url/image.jpg', title:'My pic', url:'local/url/path'}]
    ...
});

**Comment by samdunn** [comment]
With the release of 3.2.0 you can add in your own custom fields. In this case you could add a target blank if the field existed - hope that helps.
