### ISSUE TITLE
Images are not resized proportioanlly

### ISSUE THREAD

**Issue by faridjame** [buildinternet/supersized#95]
Please take a look at this website: http://mysampleconcept.com/situs4/index.php and try to resize the screen. As you can see, the images are not resized proportionally as it's done here for example: http://buildinternet.com/project/supersized/slideshow/3.2/slide.html 

I have tried to compare everything and they all seem to be similar. 

Can you tell me what the issue is?

**Comment by samdunn** [comment]
I would make sure you don't have CSS causing this - distortion happens sometimes with responsive frameworks or CSS than is interfering with Supersized's CSS.

**Comment by faridjame** [comment]
Although not an optimal solution, I was able to solve this issue by giving the the supersized image min-width and min-height

**Comment by samdunn** [comment]
Alternatively, you could make sure the CSS rules are properly scoped to make sure supersized.css rules take precedence over the additional rules - I've heard this works nicely as well.

**Comment by newyorkwebdesign** [comment]
scoped is only recognized by Chrome

**Comment by nicoandrade** [comment]
Probably the problem is that images have "max-width: 100%".
Typical of responsive frameworks.

A solution with CSS is:

<pre>
#supersized img { max-width:none; }
</pre>

**Comment by jazzsequence** [comment]
omg @nicoandrade, that stroke of brilliance just solved the problem I've been bashing my head against for the past 3 hours.

**Comment by lucygeneric** [comment]
Yes +1 for @samdunn and @nicoandrade  - for me Bootstrap was injecting max-width:100%.  Thanks kids!
