### ISSUE TITLE
Default template does not pass w3 validator

### ISSUE THREAD

**Issue by applantation** [buildinternet/supersized#97]
The code template does not pass the W3 Validator, the issues are pretty trivial (like having an & in the text and some issues with wrong ordering of elements that is not HTML conform).
http://validator.w3.org/check?uri=http%3A%2F%2Fbuildinternet.com%2Fproject%2Fsupersized%2Fslideshow%2F3.2%2Fdemo.html&charset=%28detect+automatically%29&doctype=Inline&group=0&user-agent=W3C_Validator%2F1.3

**Comment by samdunn** [comment]
This is because there are elements placed via JS (eg. each slide <li> within the #supersized <ul>), among others.

As you mentioned these are pretty trivial, and should not impact performance.

**Comment by applantation** [comment]
I think you misunderstood me. The link in my first post takes you to an assessment of HTML compliance of your demo page. The errors mentioned in there are of course not a performance problem, they are just plain wrong HTML code, which fixing on your side would be trivial and make it look better (there are lots of development shops out there that do check that HTML they generate is correct.)
- First error:  Line 52, Column 14: character "&" is the first character of a delimiter but occurred as data
                  // Size & Position  
  Easily fixable with correct escaping of the ampersand.
- Next error:
  Line 88, Column 24: document type does not allow element "style" here
  The style element simply needs to be moved into the header element.
- Next four errors: required attribute "alt" not specified
  This is simply a question if you want to show any respect for people with visual impairment.
-  Line 160, Column 28: end tag for "ul" which is not finished
  The error is reported because ul required list elements in between. Replacing ul with div makes the error disappear. Nothing stops you emitting the ul element as part of the javascript so that the resulting code will be correct.
- The last one is simply a script that needs to be moved into the body of the html.

Nice slideshow, BTW.
